[package]
name = "cymbal-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "cymbal_audio"

[dependencies]
cpal = "0.16"
crossbeam-queue = "0.3"
cymbal-core = { path = "../core" }
midir = "0.10"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Threading"] }
